# Generated by Django 5.2.8 on 2025-11-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_a', to='categories.category')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_b', to='categories.category')),
            ],
            options={
                'indexes': [models.Index(fields=['category_a', 'category_b'], name='categories__categor_344e0d_idx')],
                'unique_together': {('category_a', 'category_b')},
            },
        ),
    ]
